#!/bin/sh
set -eu
: / "${IPV6_PREFIX:=fedb:1200:4500:7800::/64}"
export IPV6_PREFIX
unshare -n sh -eu -c '
ip link set lo up
ip route add local "$IPV6_PREFIX" dev lo
ip6tables-nft -t mangle -A PREROUTING -p tcp -d "${IPV6_PREFIX}" -j TPROXY --on-ip "::ffff:127.0.0.20" --on-port 80
:>"$1"
mount --bind /proc/self/ns/net "$1"' _ "$1"
